name: gameinfo
description: An app which download games information


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.1
  flutter_rating_bar: ^4.0.1
  mocktail: ^0.3.0

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  very_good_analysis: ^3.0.0
  bloc_test: ^9.0.3

  flutter_lints: ^2.0.1
flutter:

  uses-material-design: true

  assets:
    - assets/.env